# Generated by Django 4.1.4 on 2023-01-15 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_historicalpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='patient_documents/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.patient')),
            ],
            options={
                'verbose_name': 'Patient document',
                'verbose_name_plural': 'Patient documents',
            },
        ),
    ]
