# Generated by Django 4.1.4 on 2023-01-15 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_provider', '0002_alter_careprovider_options'),
        ('patient', '0005_alter_patientdocument_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='care_provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='care_provider.careprovider'),
        ),
        migrations.AddField(
            model_name='patient',
            name='care_provider',
            field=models.ForeignKey(default='707390c1-90dc-4148-b2a5-f1d9cf214111', on_delete=django.db.models.deletion.PROTECT, to='care_provider.careprovider'),
            preserve_default=False,
        ),
    ]
